### PR TITLE
Use build-args for dynamic docker build

### PR DESCRIPTION
**Pull request by willis7**
Update the Dockerfiles to use build args for tool version and checksum value.

Opening this PR for feedback on the repo as a whole.

@mjdavies - here's some Docker for you to have fun with :-)

### CODE REVIEW

**Comment by willis7** [comment]
Good spot, the docs should have said build. I acutally think listing the docker compose commands are confusing given I'm using a makefile, so I have removed them.

Once the containers are built (using `make all`) you can run them like any other container. In each of the Dockerfiles (in the header) I have provided an example `docker run ...` for testing. Does that help?
Would there be any benefit writing a `make test` command?

**Comment by mjdavies** [comment]
I can run them like so

docker run -it onsdigital/jenkins-slave-sbt:0.13.13 /bin/bash

That starts them up ok, is that good enough?

Be good to document that though if it is

**Comment by mjdavies** [comment]
Ah, just spotted the examples :-)

Agreed on removing the docker-compose examples, if anyone wants to do that they can jump in and do it themselves.

All looks good to me Sion, I'll review and merge now.

**Comment by mjdavies** [comment]
Sorry, replying too speedily.

"Would there be any benefit writing a make test command?"

If we're going to be changing these builds, or adding builds, it probably does make sense to have a single command to run a test that all the containers build ok.

It would at least prove that any edited/uploaded code actually worked.

Think what Nigel would do!!

**Pull request merged**
